# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    # web service continues until Postgres is up
    # Once up, run previous command 
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db: # service 
    image: postgres:15-alpine
    volumes: # config to persist data beyond life of the container
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment: # set name of default database, username, password
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data: